### ISSUE TITLE
Is it normal for Subst and Dist to be left behind sometimes?

### ISSUE THREAD

**Issue by numbermaniac** [RuleBasedIntegration/Rubi#2]
Messing around with Rubi I tried to trigger [the first rule in section 8.9](https://github.com/RuleBasedIntegration/IntegrationRules/blob/master/PdfFiles/8%20Special%20functions/8.9%20Product%20logarithm%20function.pdf)  (page 1). When I tried, I noticed that, although I somehow missed the rule, it left `Subst` and `Dist` behind in the answer:
![screen shot 2018-07-16 at 6 36 46 pm](https://user-images.githubusercontent.com/5206120/42749517-45e1c3c0-8927-11e8-9c4a-0a794ab73d0c.png)

Is this intentional? I don't know much about this package, so I'm not sure if it's a bug or intended behaviour.

**Comment by halirutan** [comment]
Your result is not the same that I get. Did you load the special functions? 

```mma
$LoadElementaryFunctionRules = True;
$LoadShowSteps = True;
<< Rubi`
```

If that doesn't help, can you try the latest version that is online? We had to change the versioning a bit, so it is likely that you need to uninstall the paclet before reinstalling it:

```mma
PacletUninstall["Rubi"]
PacletInstall["https://github.com/RuleBasedIntegration/Rubi/releases/download/4.15.2.1/Rubi-4.15.2.1.paclet"]
```

then

```mma
<<Rubi`
$LoadElementaryFunctionRules = True;
$LoadShowSteps = True;
Steps@Int[(2 ProductLog[4 + 3 x])^(-2), x]
```

**Comment by numbermaniac** [comment]
Ah, I did not do `$LoadElementaryFunctionRules = True`, that is why I got that result. I see I'm now getting a full answer from it. Thanks!

**Comment by numbermaniac** [comment]
Thinking about it, It may be worth printing a warning message if the output contains incomplete `Subst`, `Dist` or `Int` expressions, and the user has not loaded the elementary functions, to suggest that they do so and try it again.
