### ISSUE TITLE
Problem with mac mohave mma11.3

### ISSUE THREAD

**Issue by andreasdieckmann** [RuleBasedIntegration/Rubi#20]
I could only get Rubi 4.16.1.0 to load the rules after I changed all \\  to /  in file Rubi.m

Greetings Andreas

**Comment by AlbertRich** [comment]
Thanks Andreas for bringing this operating system dependent bug to our attention.  It has been permanently resolved through the consistent use of the Mathematica function `FileNameJoin` that builds file names appropriate for the operating system.  A so revised version of Rubi-4.16.1.0 is now available on Rubi's website.

Aloha from Hawaii, Albert
