### ISSUE TITLE
Doubt on Miscellaneous integration rules 

### ISSUE THREAD

**Issue by Shekharrajak** [RuleBasedIntegration/Rubi#22]
I want to know more about this rule : 
https://github.com/RuleBasedIntegration/Rubi/blob/master/Rubi/IntegrationRules/9%20Miscellaneous/9.4%20Miscellaneous%20integration%20rules.m#L71

Please let me know, when it should be applied. I see it is getting applied for Integral(x,x) as well so it is returning the same `Integral(x, x)` but it should have `x**2/2` right ?

Basically I am working on SymPy intergal/rubi module and matchPy's pattern matching.

**Comment by Shekharrajak** [comment]
Original discussion: https://github.com/sympy/sympy/pull/16548#issuecomment-480284817

**Comment by AlbertRich** [comment]
"Miscellaneous integration rules.m" is the last package of integration rules to be loaded, and the rule on line 71 is the last rule in that file.  Thus that rule is only applied if NONE of the other 6600+ rules before it applies.  For your example, there is a rule for Int[x,x] so the rule on line 71 is not applied.
