### ISSUE TITLE
Weakness

### ISSUE THREAD

**Issue by mariuszi28cg** [RuleBasedIntegration/Rubi#23]
Int[(Exp[x]*(2 - x^2))/((1 - x) Sqrt[1 - x^2]), x]

Gives :

Int[E^x/Sqrt[1 - x^2], x] + Int[E^x/((1 - x) Sqrt[1 - x^2]), x] + Int[(E^x x)/Sqrt[1 - x^2], x]

Answer is: (E^x (1 + x))/Sqrt[1 - x^2]

**Comment by AlbertRich** [comment]
Hi MI.  Good to hear from the winner of Rubi's Hardest Integral Challenge!  Thanks for pointing out this deficiency in Rubi.  Mathematica 11.3 cannot integrate it either, but Maple 2018.2 can.

I will add this exponential integration problem to the Rubi's test suite, effectively adding it to my long to-do list.

Thanks, Albert
