### ISSUE TITLE
Integration of RealSign and RealAbs

### ISSUE THREAD

**Issue by amcostant** [RuleBasedIntegration/Rubi#25]
Int[RealSign[a*t + b], t]
results in 
Subst[Int[RealSign[t], t], t, b + a t]/a
when MMA does 
RealAbs[b + a t]/a

and 

Int[RealAbs[b + a t], t]
results in 
Subst[Int[RealAbs[t], t], t, b + a t]/a
when MMA does 
((b + a t) RealAbs[b + a t])/(2 a)

I understand that the number of functions where the definite integral exists is quite limited.
Thank you very much for the Rubi library

**Comment by AlbertRich** [comment]
Sorry, integrating expressions involving `RealSign` and `RealAbs` is outside the domain of expressions *Rubi* is designed to handle.

Albert
