### ISSUE TITLE
Mathematica solves this but not Rubi

### ISSUE THREAD

**Issue by Anixx** [RuleBasedIntegration/Rubi#27]
1/(1 + 2 x + x^3 - x^4)

Integrate[1/(1 + 2 x + x^3 - x^4), x] // Normal // ToRadicals // Simplify

gives sensible extensive explicit answer in elementary functions.

The same is with 
1/(1 + 2 x - x^4)
1/(x^4 + 2 x + 4)

Mathematica easily solves this: (x^4 + x^3)/(x^4 - x^3) 
with result x + 2 Log[-1 + x] but Rubi cannot. The same for  (x^4 + x^3)/(x^4 - x^2)  and (x^4 + x^2)/(x^4 - x^3)

**Comment by AlbertRich** [comment]
Sorry, Rubi can't integrate rational functions involving quartics in the denominator, unless they can be factored.

The currently available Rubi 4.16.1 easily integrates `(x^4 + x^3)/(x^4 - x^3)`, `(x^4 + x^3)/(x^4 - x^2)` and `(x^4 + x^2)/(x^4 - x^3)`.

Albert
