### ISSUE TITLE
NeQ sometimes called with only one argument

### ISSUE THREAD

**Issue by axkr** [RuleBasedIntegration/Rubi#29]
Found this line, where NeQ is called with only one argument. But where seem to be no definition for only one argument?

`NeQ[e^2 - 4*d*f]` in this line
- https://github.com/RuleBasedIntegration/Rubi/blob/26b65aa1e3adf733511df3a4d7ffb2d8709a5a9d/Rubi/IntegrationRules/1%20Algebraic%20functions/1.2%20Trinomial%20products/1.2.1%20Quadratic/1.2.1.5%20(a%2Bb%20x%2Bc%20x%5E2)%5Ep%20(d%2Be%20x%2Bf%20x%5E2)%5Eq.m#L13

**Comment by AlbertRich** [comment]
Thanks axkr for reporting this deficiency in Rubi.  It resulted in Rubi producing an unnecessarily complicated antiderivative for `Sqrt[d + e*x + f*x^2]/(a + c*x^2)^2`.  This example will now be added to the test-suite.  To fix the deficiency:
* In the file "1.2.1.5 (a+b x+c x^2)^p (d+e x+f x^2)^q", change `NeQ[e^2-4*d*f]` to `NeQ[e^2-4*d*f,0]`.

Albert
