### ISSUE TITLE
How to directly get the TeXForm of every step?

### ISSUE THREAD

**Issue by wuyudi** [RuleBasedIntegration/Rubi#34]
This is what now I do :

For example:

```mathematica
Int[x Sin[x],x]//Steps
```

![image](https://user-images.githubusercontent.com/30024051/81321555-40785e80-9082-11ea-8431-dd668033e526.png)

click one step, then paste it to .nb, then `//TeXForm` to get the TeX code. (kind of monkey job)

I've tried `FullForm`, get nothing, `// Trace` gives back a lot of things, which seems a bit hard for me to pick out what I want.

So is it possible to add a command to automatically get code like

```TeX
\begin{aligned}
\int f(x)\,dx&= ......\\
&= ......\\
......
\end{aligned}
```

to make it easier for following steps? For example , using MaTeX to get nice formula.

**Comment by wuyudi** [comment]
After some test, this is a half-done job:

```mathematica
Steps[Int[Sin[x]/x^2, x], RubiPrintInformation -> False] //
      Flatten //
     Most //
    Select[Head@# =!= RubiRule &] //
   # /. RubiIntermediateResult[x_] -> x & //
  (*ToString@*TeXForm is also OK*)
  Map["=&" <> (Convert`TeX`ExpressionToTeX[HoldForm @@ #]) <> 
     "\\\\" &] //
 StringRiffle
```

**Comment by wuyudi** [comment]
OK, I've done it.(I don't deal with the situations that Rubi failed to calculate the int)

This function returns a string.

```mathematica
SetAttributes[IntWithStepsOfTeXForm, {HoldFirst}];
IntWithStepsOfTeXForm[j_] := 
 With[{TeX2Str = Convert`TeX`ExpressionToTeX},
  Steps[j, RubiPrintInformation -> False] //
         Flatten //
        Most //
       Select[Head@# =!= RubiRule &] //
      # /. RubiIntermediateResult[x_] -> x & //
     (*ToString@*TeXForm is OK*)
     Map["=&" <> (TeX2Str[HoldForm @@ #]) <> "\\\\" &] //
    # /. {a___} -> {
        "\\begin{aligned}",
        TeX2Str@HoldForm@j,
        a,
        "\\end{aligned}"} & // StringRiffle
  ]
```

Usage:

![image](https://user-images.githubusercontent.com/30024051/81469030-572dcb00-91d2-11ea-8459-df87d2697472.png)

Or

```mathematica
IntWithStepsOfTeXForm[Int[(x + 1)/Sqrt[x^2 + 1], x]] // Print
```

And then choose and copy to clipboard.

Maybe I will make a pr for this function in the future.

**Comment by halirutan** [comment]
Yep, this is exactly what I implemented `RubiPrintInformation -> False` for so that people can create their own functions for displaying integration steps.

**Comment by wuyudi** [comment]
I make it better:

```mathematica
IntWithStepsOfTeXForm[formula_, j_]:=
With[{TeX2Str = Convert`TeX`ExpressionToTeX},
Steps[Int[formula, j], RubiPrintInformation -> False] // 
Flatten //
Most // 
Cases[RubiIntermediateResult[x_]:>"=&" <> (TeX2Str[HoldForm @@ x]) <>"\\\\"] //
{"\\begin{aligned}",TeX2Str@HoldForm@Int[formula, j], Sequence @@ #,"\\end{aligned}"} & // 
StringRiffle]
```

Now we can use it just like `Integrate`

![image](https://user-images.githubusercontent.com/30024051/81501293-2bd8d800-92c7-11ea-8f14-d787b4ae4914.png)

**Comment by asdasd1dsadsa** [comment]
By the way, I modified it to be another display function which doesn't use `TeXForm` but `TraditionalForm`:
```
IntTraditional[expr_, var_] := Style[Grid[
	{"\[LongEqual]", TraditionalForm@#}& /@ Cases[
		Flatten@First@Steps[Int[expr, var], RubiPrintInformation -> False],
		RubiIntermediateResult[x_] :> HoldForm@@x
	]// Prepend[{"",TraditionalForm@HoldForm@Int[expr,var]}]
, Alignment -> Left], FontFamily -> "Latin Modern Roman 10"];

SetAttributes[IntTraditional, HoldAll]

SyntaxInformation[IntTraditional] = {"LocalVariables" -> {"Integrate", {2, Infinity}}};

Subst /: MakeBoxes[HoldPattern@Subst[expr_,src_,tar_], TraditionalForm] := RowBox@{UnderscriptBox[StyleBox["Subs", FontSize -> Medium], RowBox[{MakeBoxes[src, TraditionalForm], "\[Rule]", MakeBoxes[tar, TraditionalForm]}]], MakeBoxes[expr, TraditionalForm]}
```

**Comment by wuyudi** [comment]
> By the way, I modified it to be another display function which doesn't use `TeXForm` but `TraditionalForm`:
> 
> ```
> IntTraditional[expr_, var_] := Style[Grid[
> 	{"\[LongEqual]", TraditionalForm@#}& /@ Cases[
> 		Flatten@First@Steps[Int[expr, var], RubiPrintInformation -> False],
> 		RubiIntermediateResult[x_] :> HoldForm@@x
> 	]// Prepend[{"",TraditionalForm@HoldForm@Int[expr,var]}]
> , Alignment -> Left], FontFamily -> "Latin Modern Roman 10"];
> 
> SetAttributes[IntTraditional, HoldAll]
> 
> SyntaxInformation[IntTraditional] = {"LocalVariables" -> {"Integrate", {2, Infinity}}};
> 
> Subst /: MakeBoxes[HoldPattern@Subst[expr_,src_,tar_], TraditionalForm] := RowBox@{UnderscriptBox[StyleBox["Subs", FontSize -> Medium], RowBox[{MakeBoxes[src, TraditionalForm], "\[Rule]", MakeBoxes[tar, TraditionalForm]}]], MakeBoxes[expr, TraditionalForm]}
> ```

Actually your don't need to `HoldAll`, because the `Integrate` doesn't have that.

```
Attributes[Integrate]
```

> {Protected, ReadProtected}

Without `HoldAll`, you can write things like `IntTraditional[list[[1]],x]`. Or you should use `IntTraditional[  Evaluate@list[[1]],x]`

**Comment by wuyudi** [comment]
Wow, amazing, After running your code, the effort is so nice! Thx. 

Maybe it's because of this line? `Subst /: MakeBoxes[HoldPattern@Subst[expr_,src_,tar_], TraditionalForm] := RowBox@{UnderscriptBox[StyleBox["Subs", FontSize -> Medium], RowBox[{MakeBoxes[src, TraditionalForm], "\[Rule]", MakeBoxes[tar, TraditionalForm]}]], MakeBoxes[expr, TraditionalForm]}`


![image](https://user-images.githubusercontent.com/30024051/81531242-e01f4080-9351-11ea-8a70-5b7caeb52336.png)

```
IntWithStepsOfTeXForm[expr_, var_] := 
 With[{TeX2Str = Convert`TeX`ExpressionToTeX}, 
  Steps[Int[expr, var], RubiPrintInformation -> False] // Flatten // 
       Most // Cases[
       RubiIntermediateResult[x_] :> 
        "=&" <> (TeX2Str[HoldForm @@ x]) <> 
         "\\\\"] // {"\\begin{aligned}", 
       TeX2Str@HoldForm@Int[expr, var], Sequence @@ #, 
       "\\end{aligned}"} & //
    StringReplace[
     "\\, d" <> ToString[var] -> "\\, \\mathrm{d}" <> ToString[var]] //
   StringRiffle]
```

**Comment by asdasd1dsadsa** [comment]
> Wow, amazing, After running your code, the effort is so nice! Thx.
> 
> Maybe it's because of this line? `Subst /: MakeBoxes[HoldPattern@Subst[expr_,src_,tar_], TraditionalForm] := RowBox@{UnderscriptBox[StyleBox["Subs", FontSize -> Medium], RowBox[{MakeBoxes[src, TraditionalForm], "\[Rule]", MakeBoxes[tar, TraditionalForm]}]], MakeBoxes[expr, TraditionalForm]}`
> 
> ![image](https://user-images.githubusercontent.com/30024051/81531242-e01f4080-9351-11ea-8a70-5b7caeb52336.png)
> 
> ```
> IntWithStepsOfTeXForm[expr_, var_] := 
>  With[{TeX2Str = Convert`TeX`ExpressionToTeX}, 
>   Steps[Int[expr, var], RubiPrintInformation -> False] // Flatten // 
>        Most // Cases[
>        RubiIntermediateResult[x_] :> 
>         "=&" <> (TeX2Str[HoldForm @@ x]) <> 
>          "\\\\"] // {"\\begin{aligned}", 
>        TeX2Str@HoldForm@Int[expr, var], Sequence @@ #, 
>        "\\end{aligned}"} & //
>  StringReplace[{"\\, d" <> ToString[var] ->  "\\, \\mathrm{d}" <> ToString[var],  "\\int" -> "\\displaystyle \\int"}]//
>    StringRiffle]
> ```

Yes, ```Convert`TeX`ExpressionToTeX``` `MakeBoxes` with `TraditionalForm` at first, so this definition for display affects the TeX output.

**Comment by Gravifer** [comment]
I made a PR ([pull-request#44](https://github.com/RuleBasedIntegration/Rubi/pull/44)) for this thread. Modifications were made to the suggestions above, and I do hope this is not offensive to the original contributors.
