### ISSUE TITLE
Additional source for error function integrals

### ISSUE THREAD

**Issue by JasonZimba** [RuleBasedIntegration/Rubi#46]
Hello, I just downloaded Rubi and it's really cool. My motivation was to see if Rubi could do an integral that Mathematica can't. Unfortunately Rubi can't do the integral, but that's OK because I found [this nice table](https://nvlpubs.nist.gov/nistpubs/jres/73b/jresv73bn1p1_a1b.pdf) online, which dates from the 1960s and includes my integral (formula 4.3.13, for what it's worth). Anyway I'm sharing the resource in case it can lead to additional rules in Rubi someday. Best, Jason

**Comment by AlbertRich** [comment]
Thanks Jason for the link to Ng & Geller's *Table of Integrals of the Error Functions* that I was not aware of.

Albert

**Comment by ValZapod** [comment]
So, you did not ix it?

**Comment by AlbertRich** [comment]
For the last several years my focus has been on perfecting the rules for integrating algebraic and elementary functions.  These are more fundamental than those for integrating special functions.

I invite you to contribute additional rules for integrating expressions involving error functions to the ones currently in [8.1 Error functions](https://rulebasedintegration.org/PdfRuleFiles/8%20Special%20functions/8.1%20Error%20functions.pdf).

Albert
