### ISSUE TITLE
Error when load on new version wolfram engine (or mathematica), version >= 12.1

### ISSUE THREAD

**Issue by wuyudi** [RuleBasedIntegration/Rubi#47]
I tried on local computer

```
12.1.0 for Linux x86 (64-bit) (April 14, 2020)
```

It load, with some error.

I then tried it on wolfram cloud.

```
13.0.0 for Linux x86 (64-bit) (November 22, 2021) 
```

```mathematica
LoadRules
::inv
:Couldnotloadfileorsection:{/wolframcloud/userfiles/d50/d5055238-6028-4d1a-a70a-b024a624b83c/Base/Paclets/Repository/Rubi-4.16.1.0/IntegrationRules/9Miscellaneous\9.1Integrandsimplificationrules.m}

LoadRules
::inv
:Couldnotloadfileorsection:{/wolframcloud/userfiles/d50/d5055238-6028-4d1a-a70a-b024a624b83c/Base/Paclets/Repository/Rubi-4.16.1.0/IntegrationRules/1Algebraicfunctions\1.1Binomialproducts\1.1.1Linear\1.1.1.1(a+bx)^m.m}

LoadRules
::inv
:Couldnotloadfileorsection:{/wolframcloud/userfiles/d50/d5055238-6028-4d1a-a70a-b024a624b83c/Base/Paclets/Repository/Rubi-4.16.1.0/IntegrationRules/1Algebraicfunctions\1.1Binomialproducts\1.1.1Linear\1.1.1.2(a+bx)^m(c+dx)^n.m}

General
:FurtheroutputofLoadRules::invwillbesuppressedduringthiscalculation.
```

If type

```mma
??Int
```

return normal result.
local
![image](https://user-images.githubusercontent.com/30024051/150588289-6f2d9264-e7c8-4417-8b1c-b91207da6a7e.png)
wolfram cloud
![image](https://user-images.githubusercontent.com/30024051/150588322-d8ce43e5-1022-45ab-afb7-aef4c40c7f75.png)

but it can't calculate.

![image](https://user-images.githubusercontent.com/30024051/150588587-6cea93f1-5a2c-4f14-815a-adc486329595.png)

**Comment by halirutan** [comment]
Your error message looks like there is a mix of `/` and `\` in the filename which might be the reason. Loading the integration rules is a crucial part to make Rubi work.

**Comment by wuyudi** [comment]
At first, I install it by https://resources.wolframcloud.com/FunctionRepository/resources/GitHubInstall/

https://www.wolframcloud.com/obj/d8ae15ff-99e0-4b52-8938-0617c4f595a1

then I use the way in manual.

it works.

https://www.wolframcloud.com/obj/c7d25428-12f6-4bd2-a5ff-dcd8f607d2d3

So there may be some problem with `GitHubInstall`, Rubi itself has no problem.
