### ISSUE TITLE
Log Integral error?

### ISSUE THREAD

**Issue by paulcabbott** [RuleBasedIntegration/Rubi#48]
In Version 4.16.1.0 the following integral is incorrect:
`Int[Log[1 - x] Log[1 + x], {x, 0, 1}]`
This disagrees with Mathematica and also with Version 4.16.0.4.

**Comment by AlbertRich** [comment]
Thanks Paul for reporting this bug in Rubi 4.16.1.0.  It has been found and fixed for inclusion in the next release of Rubi.

Albert
