### ISSUE TITLE
warning message when `Needs`

### ISSUE THREAD

**Issue by AlexanderZ11234** [RuleBasedIntegration/Rubi#5]
After `PacletInstall`, running `Needs["Rubi`"]` gets below warning message:

Syntax::sntue: Unexpected end of file (probably unfinished expression) 
     (line 47 of "C:\Users\<user>\AppData\Roaming\Mathematica\Paclets\Repository\Rubi-4.15.2.
     1\IntegrationRules\9.1 Integrand simplification rules.m").

**Comment by halirutan** [comment]
That is quite odd and indicates that this file is corrupted. We have tested Rubi on Windows, Mac, and Linux and this issue never appeared. I have released the new Rubi version some seconds ago. Can you please try the following

Uninstall your Rubi version with

```mma
PacletUninstall["Rubi"]
```

Install the new version with 

```mma
PacletInstall[
  "https://github.com/RuleBasedIntegration/Rubi/releases/download/4.16.0.2/Rubi-4.16.0.2.paclet"
]
```

and then try 

```mma
<<Rubi`
```

In addition, what Mathematica version are you using?

**Comment by AlexanderZ11234** [comment]
@halirutan Thank you! It works. My MMA is v11.3.
