### ISSUE TITLE
`NeQ` function not defined as unary function in 4.17.3

### ISSUE THREAD

**Issue by axkr** [RuleBasedIntegration/Rubi#52]
For the `NeQ[e^2-4*d*f]` call I can't find a unary function definition:

https://github.com/RuleBasedIntegration/Rubi/blob/f7fa0fd7bfacd326bc9e125473c5bad41cfad4e4/Rubi/IntegrationRules/1%20Algebraic%20functions/1.2%20Trinomial%20products/1.2.1%20Quadratic/1.2.1.4%20(a%2Bb%20x%2Bc%20x%5E2)%5Ep%20(d%2Be%20x%2Bf%20x%5E2)%5Eq.m#L124

Only a binary definition is available:

https://github.com/RuleBasedIntegration/Rubi/blob/f7fa0fd7bfacd326bc9e125473c5bad41cfad4e4/Rubi/IntegrationUtilityFunctions.m#L368

**Comment by axkr** [comment]
The same case for `EqQ[m+1/2]` used as unary function?

https://github.com/RuleBasedIntegration/Rubi/blob/f7fa0fd7bfacd326bc9e125473c5bad41cfad4e4/Rubi/IntegrationRules/1%20Algebraic%20functions/1.2%20Trinomial%20products/1.2.4%20Improper/1.2.4.2%20(d%20x)%5Em%20(a%20x%5Eq%2Bb%20x%5En%2Bc%20x%5E(2%20n-q))%5Ep.m#L45

**Comment by halirutan** [comment]
Looks like a typo to me, too. My best guess is that Albert meant to write `NeQ[e^2, 4*d*f]` or `NeQ[e^2-4*d*f, 0]` in the first case and something similar in the second. But I can't be sure. @stblake, do you have any idea?

**Comment by stblake** [comment]
Fixed.
