### ISSUE TITLE
Integration that MMA can do but Rubi Cannot

### ISSUE THREAD

**Issue by ackinetics** [RuleBasedIntegration/Rubi#7]
This [thread](http://community.wolfram.com/groups/-/m/t/1438484) discusses an integral that I tried in Rubi but it failed to find an answer.  Regards

**Comment by halirutan** [comment]
For reference, this is the integral Rubi cannot solve

```mma
 Integrate[Sqrt[a + (b*Sin[x] + c Cos[x])^2], x]
```

**Comment by halirutan** [comment]
@ackinetics Thank you for your report. We will add this form to the test-suite and next time Albert is working on trigonometric integration, he will try to fix this. For the moment, you can use Mathematica 11.3 as it is able to find an antiderivative for this expression.

**Comment by ackinetics** [comment]
No problem!  I like the work you are doing. The critical realization is that a*sin(x) + b*cos(x) -> c*sin(x+d)

Regards

**Comment by AlbertRich** [comment]
@ackinetics Thanks for reminding me of the identity I derived a while back:
```mma
a*Sin[z] + b*Cos[z] == Sqrt[a^2 + b^2]*Sin[z + ArcTan[a, b]]
```
which is valid for all a, b and z throughout the complex plane.  The next version of Rubi will use this identity so
```mma
Int[Sqrt[a + (b*Sin[x] + c Cos[x])^2], x]
```
will evaluate to
```mma
Sqrt[a]*EllipticE[x + ArcTan[b, c], -(b^2 + c^2)/a]
```
if a>0, and if not to
```mma
(Sqrt[a + (c*Cos[x] + b*Sin[x])^2]/Sqrt[(a + (c*Cos[x] + b*Sin[x])^2)/a])*
   EllipticE[x + ArcTan[b, c], -(b^2 + c^2)/a]
```
This will make the original definite integral problem in the Wolfram Community thread
```mma
Int[Sqrt[a + (b*Sin[x] + c Cos[x])^2], {x, n - Pi, n}]
```
trivial for the next version of Rubi.

Albert

**Comment by jaswin90** [comment]
Rubi is not integrating, 
`Int(cos(y/2 - Subscript[\[Theta], 2]/2) cot(x/2 - y/2) csc^3(
   x/2 - y/2), y)`
but Mathematica does.
